name: Main workflow
on: push
jobs:
  build:
    name: Dockerfile-action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/dockerfile-action
        with:
          A_NAME: "Sharona"
