name: Main workflow
on: push
jobs:
  build:
    name: Dockerfile-action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Run Makefile
        env:
          INPUT_A_NAME: ${{ secrets.INPUT_A_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make push-report
