name: Main workflow
on: push
jobs:
  build:
    name: Dockerfile action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions
        with:
          MY_NAME: "Sharona"
